package:
  name: sfincs
  version: "0.1.0"

source:
  path: ./repo/source
  use_gitignore: true

build:
  number: 0

requirements:
  build:
    - ${{ compiler('fortran') }}
    - ${{ compiler('c') }}
    - autoconf
    - automake
    - libtool
    - m4
    - make
    - pkg-config
  host:
    - libnetcdf * mpi_openmpi_*
    - hdf5 * mpi_openmpi_*
    - openmpi
    - libgfortran

tests:
  - script:
      - test -f $PREFIX/bin/sfincs
